version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - bash requirements/install.sh docs
      - . .venv/bin/activate

sphinx:
  configuration: docs/source-zh/conf.py
  fail_on_warning: true
